### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by Icy-cai** [Icy-cai/BigBuck#1]
We are going to divide our Bigbucks project into four parts:
Display(View), Model(database),Controller(function, api),YahooFinance

First Week: Display and function
Second Week:Function/api and database
Third Week:YahooFinance and Adding more UI/UX
Fourth Week: Finishing all functions and features and making videos, wrapping up

**Comment by kl370** [comment]
we drew uml diagrams and planned the flow of the objects
we designed the ui/ux of the websites and decides its functions
